### ISSUE TITLE
Datepicker does not show any numbers in the popup

### ISSUE THREAD

**Issue by antonsimola** [valor-software/ng2-bootstrap#5084] opened 2019-02-28 14:32 UTC
### Bug description or feature request:

Date picker shows only DDDD, MMM in the popup

![image](https://user-images.githubusercontent.com/8913934/53573512-4e754a00-3b76-11e9-9f77-83539678470a.png)

ngx-bootstrap: 3.3.0

Angular: 7.2.7

Bootstrap: 4.1.0

Angular CLI

**Comment by robjean9** [comment] 2019-03-08 19:00
I'm having the same issue. If you solve your please post the solution. But I think that is a Bug DatePicker.

**Comment by antonsimola** [comment] 2019-03-14 08:36
Currently we are using older version to avoid this (3.0.1)

**Comment by ludmilanesvitiy** [comment] 2019-03-19 14:05
@antonsimola @robjean9 Please provide a reproduction via stackblitz

Starter templates:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by Domainv** [comment] 2019-03-20 12:57
Closes as a duplicate of #5086

**Closed as completed by Domainv** 2019-03-20 12:57 UTC
Labels: comp(datepicker), needs: reproduce
