### ISSUE TITLE
Error with onBlur in empty Typeahead

### ISSUE THREAD

**Issue by rgbweb** [valor-software/ng2-bootstrap#5736] opened 2020-03-30 10:50 UTC
Hi,

my browser console points me to an error when I focus and unfocus a Typeahead input field without typing anything into it.

This is repoducable with all example inputs at the official docs page:
https://valor-software.com/ngx-bootstrap/#/typeahead

Repro steps:
1. Open the console of your browser developer tools
2. Set your cursor into the first example input to focus it
3. (DO NOT type anything)
4. Click anywhere else on the page to lose focus
5. Have a look at the error in the console:
In Chrome: ![image](https://user-images.githubusercontent.com/3253452/77903158-b4a13480-7282-11ea-869b-6572d74d62fa.png)
In Firefox: ![image](https://user-images.githubusercontent.com/3253452/77903284-e1554c00-7282-11ea-9b79-33bcf690dcd5.png)

The error occures while trying to read the length of the undefined `_matches` array in the `onBlur` method of the typeaead: https://github.com/valor-software/ngx-bootstrap/blob/6047bcece88162e508f76e2b091d66badd682eca/src/typeahead/typeahead.directive.ts#L306

The same problem occurs with an asnyc typeahead when the user enters something into the input and blurs the input immediately without waiting for the results list.

Fortunately, the user does not see any error and the typeahead does not stop working at all. But console errors can be a problem in applidations when the client errors are sent to a backend.

Versions: (same as the offical docs at 2020/03/30)
```
ngx-bootstrap 5.6.0
bootstrap 4
```

**Comment by boloboloda** [comment] 2020-03-31 06:33
same issue.

**Comment by Theyssen** [comment] 2020-04-08 15:29
I am having the same issue.

I created a minimal stackblitz using the docs to reproduce the issue: 
Stackblitz: https://stackblitz.com/edit/angular-hdod7r
Docs: https://valor-software.com/ngx-bootstrap/#/typeahead#async-data

Use the same steps as mentioned above to reproduce the issue.

**Comment by Theyssen** [comment] 2020-05-26 08:48
Is there more news on this bug?

**Comment by ArturKwiatkowski** [comment] 2020-05-28 08:54
I'm facing the same issue. Is there any temporary workaround for this until the fix is merged?

**Closed as completed** 2020-05-29 10:37 UTC

**Comment by rgbweb** [comment] 2020-05-30 08:52
Thanks @daniloff200

**Comment by sponkrashin** [comment] 2020-05-30 21:55
Does anybody know when new package version will be available?

**Comment by mcicco** [comment] 2020-06-18 10:06
Same issue, any update?

**Comment by CharlesDeJager** [comment] 2020-07-24 20:13
Any idea on when this will be fixed?

**Comment by daniloff200** [comment] 2020-07-25 13:18
Should be available in 6.0.0, please, check

**Comment by DerZyklop** [comment] 2020-08-04 15:35
✓ It works for me with 6.0.0
