### ISSUE TITLE
Popover triggers="focus" doesn't work on non-buttons

### ISSUE THREAD

**Issue by custompro12** [valor-software/ng2-bootstrap#5601] opened 2020-01-16 17:45 UTC
### Bug description:

Plunker/StackBlitz that reproduces the issue:
1. Load the StackBlitz from the [Dismiss on Next](https://valor-software.com/ngx-bootstrap/#/popover#popover-dismiss) example
2. Note proper behavior of popover with `triggers="focus"` when element is a `button`
3. Open `app/dismiss.html`
3. Change the `button` to a `div` on lines 1 and 6
4. Popover no longer works

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 5.4.0
Angular: 8.0
Bootstrap: 4.0.0

### **Expected behavior**

Popover to work with other HTML elements the same way it works with HTML buttons

**Comment by IraErshova** [comment] 2020-01-23 14:01
Hi @custompro12 ! Could you please check [this issue](https://github.com/valor-software/ngx-bootstrap/issues/5613)? It reports the same problem.

I closed this issue because it's not a bug of ngx-bootstrap. You have to use only focusable elements.

**Closed as completed by IraErshova** 2020-01-23 14:01 UTC
Labels: comp(popover), won't fix

**Comment by custompro12** [comment] 2020-01-23 18:01
Hi @IraErshova ,

Thanks for the info.  Based on your [link](https://html.spec.whatwg.org/multipage/interaction.html#focusable) I see that I need to make the div focusable by the browser.

Therefore, the real answer to my issue is to add a `tabindex="-1"` to the div.  Then everything works.  Thanks again!
