### ISSUE TITLE
bsDatepicker Doesn't Return Focus to Calling Element

### ISSUE THREAD

**Issue by JackWolfgangIIR** [valor-software/ng2-bootstrap#5619] opened 2020-01-24 17:06 UTC
Using the bsDatepicker, when a user selects a date, the focus is not returned to the input element with which the datepicker is associated.

ngx-bootstrap 5.30
Angular 8.0.0
Bootstrap 4.3

**Expected behavior**

1.  User clicks into the input.  The datepicker popup appears.
1.  The user clicks a date on the calendar, and the popup disappears.
1.  Instead of returning the user's focus to the input element, they are returned to the top of the page.

Behavior can be reproduced on the bsDatepicker documentation page:
https://valor-software.com/ngx-bootstrap/#/datepicker#value-change-event

**Comment by daniloff200** [comment] 2020-01-30 16:04
That looks like duplicate of #4472 
I hope to pick this one for next release !

**Closed as completed** 2020-01-30 16:04 UTC
Labels: enhancement, comp(datepicker), prio: low

**Comment by JackWolfgangIIR** [comment] 2020-01-30 16:06
@daniloff200, sorry I didn't see the other entry.  Thanks for the feedback!

**Comment by daniloff200** [comment] 2020-01-30 16:06
@JackWolfgangIIR  no worries !
