### ISSUE TITLE
Datepicker input automatically changes the displayed value

### ISSUE THREAD

**Issue by daniel-seitz** [valor-software/ng2-bootstrap#6085] opened 2021-05-07 13:59 UTC
**Bug description:**
Written input is automatically changed when the minDate /maxDate is specified and the written value is invalid
In v5.4 it still worked as expected
In v5.5 it broke

This is especially wrong since the formControl.value stays as written, and also the ngModelChange event emits that written date

**Reproduce:**
Go to: https://valor-software.com/ngx-bootstrap/old/5.5.0/#/datepicker#min-max
Type in an invalid date (1.1.) and leave the input (TAB-key)
-> The value of the input is automatically changed to minDate

_Working example:_
Go to: https://valor-software.com/ngx-bootstrap/old/5.4.0/#/datepicker#min-max
Type in an invalid date (1.1.) and leave the input (TAB-key)
-> Written value stays as it was typed in

This issue is likely related to https://github.com/valor-software/ngx-bootstrap/issues/6066

**Versions**
see above

****Expected behavior****
The value should not automatically change.

_For us its a critical issue, think of long questionnaires with personal health information dealing with automatic payments in a big business environment - please let me know if I can/should support on this_

**Comment by markusvorraber** [comment] 2021-09-09 11:05
I am facing the same issue with v7.0.0

**Comment by Et3rnal** [comment] 2022-02-02 08:32
Same here, very bad!
I'm on `5.6.2`

~~Since the date picker got removed in V8 I don't think this will be fixed.~~
Sorry, I think the issue is the new `BsDatepicker`

Looks like the issue is still there in V8, automatically updating invalid dates (before the minimal/after the max) to the current min/max value is just wrong!

**Comment by WillemDeNys** [comment] 2022-09-08 10:21
Is this going to be fixed? We need to be able to show a message indicating the date they wrote is before or after the min/max date. We don't want it to be magically updated without the user is being notified. At least provide an option to disable the automatic update.

**Comment by gslusarek-cic** [comment] 2022-09-30 14:12
This issue should be top priority, currently this date picker is unusable.

**Comment by aliabbaszade1990** [comment] 2023-01-13 11:48
same issue "ngx-bootstrap": "9.0.0",

**Comment by aliabbaszade1990** [comment] 2023-01-13 11:54
same issue "ngx-bootstrap": "9.0.0",

**Closed as completed** 2023-02-08 19:03 UTC
Labels: comp(datepicker)
