### ISSUE TITLE
Latest version on home page site is 5.6.2 and not 6.x.x

### ISSUE THREAD

**Issue by klimowskict** [valor-software/ng2-bootstrap#5892] opened 2020-08-05 20:14 UTC
The home page for ngx-bootstrap is showing 5.6.2 as the most recent version instead of a 6.x.x version.

![image](https://user-images.githubusercontent.com/35943596/89459497-91e5c780-d71d-11ea-9fc6-b3dd0f9b9fb2.png)

**Comment by daniloff200** [comment] 2020-08-06 16:12
Ah, yes, that's a known one.
Something was broken during the last 6.0.0 deploy, and we're still on it
Hope it will be fixed after the next release

**Comment by daniloff200** [comment] 2020-08-07 07:12
Actually, it's even duplicate of #5802 , so ,gonna close this one

**Closed as completed by daniloff200** 2020-08-07 07:12 UTC
