### ISSUE TITLE
Typeahead list with [typeaheadMinLength]="0" does not appear on focus

### ISSUE THREAD

**Issue by RihabEA** [valor-software/ng2-bootstrap#6065] opened 2021-04-08 09:34 UTC
Angular version "11.0.3",
"bootstrap": "4.5.3",

<input #input type="search"
               [required]="required"
               [(ngModel)]="text"
               [typeahead]="list"
               [typeaheadMinLength]="0"
/>

when we focus on the field, the list doesn't appear, the  [typeaheadMinLength] = "0" not working

**Comment by valorkin** [comment] 2021-09-10 10:41
sry, closing as can't reproduce
please see here https://valor-software.com/ngx-bootstrap/#/typeahead#reactive-forms
if you are able to provide a stackblitz with reproduction it would be great

**Closed as completed by valorkin** 2021-09-10 10:41 UTC
Labels: comp(typeahead), can be closed?
