### ISSUE TITLE
backdrop issue with nested modals

### ISSUE THREAD

**Issue by SusanneEmineo** [valor-software/ng2-bootstrap#6686] opened 2024-09-25 11:51 UTC
Bug description:

When working with nested modals, the backdrop disappears when the first modal is hidden, even though there are still modals open. Following disappears in the html, thus the background blurring is lost:
`<bs-modal-backdrop class="modal-backdrop fade show"></bs-modal-backdrop>`

The issue is actually visible in the demo of the current ngx-bootstrap version: https://valor-software.com/ngx-bootstrap/#/components/modals#service-nested: Open first modal -> Open second modal -> Close self / Close first modal (in either case)

I tried a manual workaround counting levels of modals and calling `this.bsModalService._showBackdrop();` in case there are still modals open, but that does not work.

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 18.0.2

Angular: 18.2.0

Bootstrap: 5.3.3

Build system: Angular CLI

**Expected behavior**

I expect the backdrop to remain until the last modal ist hidden.

**Comment by dur00s** [comment] 2024-09-26 08:11
Experiencing the same, only difference is that we are using Angular 18.1.0

**Comment by rogerwilcos83** [comment] 2024-09-26 13:14
I can confirm I have the same issue. I am on ngx-bootstrap 18.0.2, angular 18.2.5. Any workaround would be appreciated if available.

**Comment by frenzymind** [comment] 2024-10-02 06:53
Same here

**Comment by Gillardo** [comment] 2024-10-09 08:27
same issue

**Comment by serhatuysal** [comment] 2024-10-09 22:01
I solved it this way for now, and it seems to be working. 

openModal(
    content: any,
    options?: ModalOptions
  ): BsModalRef {
    const modal = this.bsModalService.show(
      content,
      {
        class: 'modal-sm',
        animated: false,
        backdrop: 'static',
        ...options
      },
    );
    modal.onHide.subscribe(() => {
      debugger;
      const openModals = this.bsModalService.getModalsCount();
      if (openModals > 0) {
        this.addCustomBackdrop();
      } else {
        this.removeCustomBackdrop();
      }
    });
     return modal;
  }
  addCustomBackdrop() {
    const backdrop = this.renderer.createElement('bs-modal-backdrop');
    this.renderer.addClass(backdrop, 'modal-backdrop');
    this.renderer.addClass(backdrop, 'show');
    this.renderer.appendChild(document.body, backdrop);
  }

  removeCustomBackdrop() {
    const backdrop = document.querySelector('bs-modal-backdrop');
    if (backdrop) {
      backdrop.remove();
    }
  }

**Comment by lexasq** [comment] 2024-10-16 12:59
Hi. Today was introduced version 18.1.0 and fix for this was a part of it. Thanks for reporting!

**Closed as completed** 2024-10-16 12:59 UTC
