### ISSUE TITLE
bsDaterangePicker is not working with minMode set to Month

### ISSUE THREAD

**Issue by vishranti5** [valor-software/ng2-bootstrap#5273] opened 2019-06-14 13:08 UTC
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by vishranti5** [comment] 2019-06-14 13:17
I have used bsDaterangePicker of ngx-bootstrap. I wanted it is for selecting months only. so set minMode as 'month'. but it is not working. It is just increasing year in right datepicker after selecting month.

Simple DatePicker of ngx-bootstrap is working fine with minMode set to 'month'. The problem is with only DateranePicker.

Component.Html :- 

`<input type="text"
           placeholder="Daterangepicker"
           class="form-control"
		   bsDaterangepicker  [(ngModel)]="bsRangeValue" (ngModelChange)="onChange($event)"  [bsConfig]="{ rangeInputFormat: 'MMM-YYYY', containerClass: 'theme-blue',minMode:'month'}" [outsideClick]="true">`

component.ts :-

`bsValue = new Date();
  bsRangeValue: Date[];
  maxDate = new Date();


constructor(private findingService: FindingService) {
   this.bsValue.setMonth(0);
   this.bsValue.setFullYear(2019);
   this.maxDate.setMonth(2);
   this.maxDate.setFullYear(2019);
    this.bsRangeValue = [this.bsValue,this.maxDate];
  }`

![DaterangePicker](https://user-images.githubusercontent.com/40062718/59511804-db010980-8ed4-11e9-934f-2eff86c12d88.PNG)

**Comment by ludmilanesvitiy** [comment] 2019-07-11 11:57
Duplicate of https://github.com/valor-software/ngx-bootstrap/issues/5006

**Closed as completed by ludmilanesvitiy** 2019-07-11 11:57 UTC
Labels: issue, comp(datepicker)
