### ISSUE TITLE
Carousel: Reset time-out when clicking on arrow or the bottom indicators

### ISSUE THREAD

**Issue by brechtb86** [valor-software/ng2-bootstrap#5201] opened 2019-05-12 17:34 UTC
I noticed that if you click one of the arrows of indicators, the timout for the next slide isn't reset. The problem with this is that if there is a time-out of 10 seconds, and you click the arrow after 9 seconds, you only see the this slide for 1 second and then it immediatly goes to the next slide.

Can you provide a fix for it?

**Comment by ludmilanesvitiy** [comment] 2019-05-21 11:13
Duplicate of #4853

**Comment by gioboa** [comment] 2019-05-22 11:34
Hi @ludmilanesvitiy I have the same problem.
Can I send a PR for it? :+1:

**Comment by ludmilanesvitiy** [comment] 2019-05-22 13:48
@gioboa Hi! Sure, please do!

**Comment by Domainv** [comment] 2019-05-23 07:53
Closes as duplicate of #4853

**Closed as completed by Domainv** 2019-05-23 07:53 UTC
Labels: comp(carousel), duplicate
