### ISSUE TITLE
setting min and max date shows the end date but not the start date

### ISSUE THREAD

**Issue by school-coder** [valor-software/ng2-bootstrap#5266] opened 2019-06-12 09:55 UTC
I am trying to set the min date and max date for date range picker ( 1st Jan 1979 to 31st Jan 1979). On doing this configuration, I am seeing the max date which is not intuitive. Start date needs to be shown.

StackBlitz URL
https://stackblitz.com/edit/angular-t6tnqh

**Comment by ludmilanesvitiy** [comment] 2019-06-12 12:14
Closed as a duplicate of https://github.com/valor-software/ngx-bootstrap/issues/5265

**Closed as completed by ludmilanesvitiy** 2019-06-12 12:14 UTC
Labels: comp(datepicker), feat-request, duplicate
