### ISSUE TITLE
Angular 15 support coming?

### ISSUE THREAD

**Issue by heitorseesdragons** [valor-software/ng2-bootstrap#6523] opened 2022-11-19 20:57 UTC
Doesn't work with Angular 15

**Comment by Rich-Hopkins** [comment] 2022-11-19 23:32
I find it funny that you mention slack. My question from 9/27 is yet unanswered, and I haven't seen a question answered there since that time.

From: heitorseesdragons ***@***.***>
Sent: Saturday, November 19, 2022 3:58 PM
To: valor-software/ngx-bootstrap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [valor-software/ngx-bootstrap] Angular 15 support coming? (Issue #6523)


Before opening an issue, please search for duplicates (opened and closed) https://github.com/valor-software/ngx-bootstrap/issues<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvalor-software%2Fngx-bootstrap%2Fissues&data=05%7C01%7C%7C2276c487fc774d095ef708daca70b9f9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638044882769953571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0kMtKVQ0yINyDFcPd11CNNlEaBXeEI5DVD9NAEsBFLw%3D&reserved=0> There's no need to open an issue here if you want to ask general question, use StackOverflow or Slack instead

Bug description:

Plunker/StackBlitz that reproduces the issue:

Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplnkr.co%2Fedit%2F0NipkZrnckZZROAcnjzB%3Fp%3Dpreview&data=05%7C01%7C%7C2276c487fc774d095ef708daca70b9f9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638044882769953571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CtaX3ubldldkFW9tfsqZbseRzMkRPyIHPzalMsQWKOE%3D&reserved=0>

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackblitz.com%2Fedit%2Fngx-bootstrap%3Ffile%3Dapp%252Fapp.module.ts&data=05%7C01%7C%7C2276c487fc774d095ef708daca70b9f9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638044882769953571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7zFiU4V0GkqB%2Bi74MwlPsFakwPjuVZwxxfZNBIORSwM%3D&reserved=0>

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

Build system: Angular CLI, System.js, webpack, starter seed:

Expected behavior

A clear and concise description of what you expected to happen.

-

**Comment by heitorseesdragons** [comment] 2022-11-20 00:06
I didn't mention anything. That iis the default text that I didn't realize I had to delete. Since Angular 15 is just a few days old, and a search for it here did not mention a fix, I just left the simple question.

**Comment by heitorseesdragons** [comment] 2022-11-20 00:32
They say in the docs that ngx-bootstrap 10.0.0 is needed for Angular 15, but can't install that via npm i. How can I use 10.0.0?

**Comment by Pax90** [comment] 2022-11-26 12:48
ngx-bootstrap 10 is a future release that has not yet been released.

**Comment by SvetlanaMuravlova** [comment] 2022-11-30 21:23
yeah, you are right, you need version 10, i believe it will be released soon, thank you for your waiting

**Closed as completed by SvetlanaMuravlova** 2022-11-30 21:23 UTC

**Comment by ChrisTorng** [comment] 2022-12-01 01:36
I use `npm install --force` to install Angular 15 with ngx-bootstrap 9.0.0, it works in our project. Still hope to have officially compatible 10.0.0. Thanks alot.
