### ISSUE TITLE
typeaheadSelectFirstItem should not show first item as selected when set to false

### ISSUE THREAD

**Issue by hisham** [valor-software/ng2-bootstrap#5061] opened 2019-02-13 16:43 UTC
### Bug description or feature request:

See attached screenshot. First item is selected but pressing enter does not select the first item. This is non-intuitive. Instead, nothing should be selected when typeaheadSelectFirstItem is set to false, and user can press down and enter to select. Related to https://github.com/valor-software/ngx-bootstrap/pull/4631 and https://github.com/valor-software/ngx-bootstrap/issues/3965

<img width="311" alt="angular bootstrap 2019-02-13 09-40-56" src="https://user-images.githubusercontent.com/81853/52727911-7ad47800-2f73-11e9-9557-10bbeed812f5.png">

### Plunker/StackBlitz that reproduces the issue:
See https://valor-software.com/ngx-bootstrap/#/typeahead#selected-first-item

**Comment by valorkin** [comment] 2019-02-13 17:12
this is as designed behavior
"it doesn't select first item on focus lost" but still allows a quick UX flow "tab(select input) - enter - tab(next input)"

**Comment by hisham** [comment] 2019-02-13 17:36
This is not working for me: ""tab(select input) - enter - tab(next input)""

I'm trying it here: https://valor-software.com/ngx-bootstrap/#/typeahead#selected-first-item

I tab into the input, type 'a', press enter, press tab, and "Alabama" is not selected.

**Comment by valorkin** [comment] 2019-02-13 20:12
@svetoldo4444ka please explain intended behavior

**Comment by ghost** [comment] 2019-02-15 10:16
@hisham hi
`typeaheadSelectFirstItem = false` doesn't mean that first item doesn't have active state(active class). It means first item will not be selected if you click `Tab` or `Enter` after typeahead list was opened.
It was decided to make such behavior: 
`typeaheadSelectFirstItem = true` (by default)-https://drive.google.com/file/d/1ipxHAqYtaDoYw4_rFY5zrUZT3YYy4kZ0/view
`typeaheadSelectFirstItem = false` https://drive.google.com/file/d/147Ge6fQfJPgKNJVH8dETa9M3ddXc-xqJ/view

**Comment by hisham** [comment] 2019-02-15 16:24
Why give it active state then if it won't be selected when you press Enter? This is completely un-intuitive and not user friendly. What's the point of giving active state?

**Comment by hisham** [comment] 2019-02-15 18:31
Thanks for all your work on this and the explanation guys. I ended up moving to https://ng-select.github.io/ng-select#/data-sources which met my needs more. They have a [selectOnTab] attribute which controls whether an item is selectable on tab or not.

**Comment by maurizi** [comment] 2019-02-15 19:49
I'd note @hisham's desired UX was what was in PR https://github.com/valor-software/ngx-bootstrap/pull/3983 and also what I outlined as our preferred UX change in https://github.com/valor-software/ngx-bootstrap/issues/3965.

Is there any way this decision can be revisited? I agree @hisham that the current UX with `typeaheadSelectFirstItem = false` isn't very intuitive.

**Comment by Domainv** [comment] 2019-02-15 20:11
@maurizi I'll take a look as soon as possible by priority

**Comment by user753** [comment] 2019-03-13 13:45
@Domainv Is there any news? Or maybe some workaround like removing selection through some inner methods?

**Comment by Domainv** [comment] 2019-03-25 15:00
@user753 @maurizi @hisham
The behavior will be fixed or added as new

**Closed as completed** 2019-04-02 11:02 UTC
Labels: comp(typeahead)
