### ISSUE TITLE
ngx-boostrap tabDirective (remove event)

### ISSUE THREAD

**Issue by DebolaA** [valor-software/ng2-bootstrap#5372] opened 2019-08-30 09:32 UTC
I want the tabs to be removable, but want user confirmation before closing tab. 
Is there a way to prevent tab closing after the tab close button is clicked?

<tabset #resourceTabs>
                <tab *ngFor="let tabz of tabs"
                        [heading]="tabz.title"
                        [active]="tabz.active"
                        (selectTab)="onSelectTab($event, tabz)"
                        (deselect)="tabz.active = false"
                        [disabled]="tabz.disabled"
                        [removable]="tabz.removable"
                        (removed)="closeTabHandler(tabz, closeTabConfirmation, $event)"
                        [customClass]="tabz.customClass">
                        <edit-resources [resource]="( selectedResource)" 
                            (onTabContentChanged)="onTabContentChanged($event)"></edit-resources>
                </tab>
            </tabset>

**Comment by ludmilanesvitiy** [comment] 2019-09-16 07:38
Closed as a duplicate of https://github.com/valor-software/ngx-bootstrap/issues/786

**Closed as completed by ludmilanesvitiy** 2019-09-16 07:38 UTC
Labels: comp(tabs), feat-request
