### ISSUE TITLE
Add Keyboard Navigation to Drop Down Menu

### ISSUE THREAD

**Issue by cofad** [valor-software/ng2-bootstrap#5555] opened 2019-11-22 15:45 UTC
Currently it is only possible to navigate the drop down menu items with tab key or mouse. It would be very helpful to be able to use the up and down arrows to navigate the drop down menu.

**Comment by daniloff200** [comment] 2020-01-31 13:25
duplicate of #4015 

That should be closed vid #4156 , but, for now it needs fix

**Closed as completed by daniloff200** 2020-01-31 13:25 UTC
Labels: enhancement, comp(dropdown), duplicate
