### ISSUE TITLE
[locale] Khronos locale error: please load locale "de" before using it

### ISSUE THREAD

**Issue by abhilashsandi** [valor-software/ng2-bootstrap#5056] opened 2019-02-12 12:47 UTC
### Bug description:

In ngx-bootstrap.es2015.js bundle, defineLocale and loadLocale is defined two times.

So, when we are importing defineLocale and calling it, locales object is registering the new locale.
On using datepicker, it is calling other loadLocale method (loadLocale$1) which have no locales loaded.
This is resulting in error: Khronos locale error: please load locale "de" before using it.

We are not using angular build. We are using rollup with ngx-bootstrap.es2015.js file.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.2.0

Angular: 7.2.2

Bootstrap: 3.3.7

### Build system:
Angular cli with tsc compilation es2015 and rollup

**Comment by ludmilanesvitiy** [comment] 2019-03-19 15:50
@abhilashsandi Could you, please reproduction of this issue? Starter templates:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts
@Domainv Could be related to #5086

**Comment by Domainv** [comment] 2019-03-20 12:55
Closes as a duplicate of #5086

**Closed as completed by Domainv** 2019-03-20 12:55 UTC
Labels: needs: reproduce, feat(chronos)
