### ISSUE TITLE
Custom size of bs modal

### ISSUE THREAD

**Issue by t-zander** [valor-software/ng2-bootstrap#4601] opened 2018-09-10 06:45 UTC
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:
How do I change size of modal (what if I need modal, with size more than just lg?)
### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:
6
Bootstrap:
4

**Comment by Joklogh** [comment] 2018-09-20 10:13
Hi @t-zander 
You can use CSS classes to set size of modal. You can either append your own class by passing string in modal options. For example : `this.modalService.show(ComponentToShow, {class : 'yourOwnClass'})` and then style your class or using already provided classes : modal-content - for whole dialog; modal-header; modal-body. You can also inspect modal in developer console to see how modal looks in HTML.

P.S : you can also use css classes which uses bootstrap

**Comment by Domainv** [comment] 2018-09-28 09:03
duplicate of #4562

**Closed as completed** 2018-09-28 09:04 UTC
