### ISSUE TITLE
TypeError: this._store.select(...).filter is not a function

### ISSUE THREAD

**Issue by diegoserrat** [valor-software/ng2-bootstrap#4831] opened 2018-11-22 19:10 UTC
### Bug description or feature request:
I`m upgrading my system from angular 5 to angular 7, and I got this error when I tried to use the ngxdatepicker i`ve got this error 

ERROR TypeError: this._store.select(...).filter is not a function
    at BsDatepickerEffects.push../node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.effects.js.BsDatepickerEffects.setBindings (bs-datepicker.effects.js:46)
    at BsDatepickerContainerComponent.push../node_modules/ngx-bootstrap/datepicker/themes/bs/bs-datepicker-container.component.js.BsDatepickerContainerComponent.ngOnInit (bs-datepicker-container.component.js:42)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.5

Angular: 7.0.0 

Bootstrap: 4.0.0

### Build system: Angular CLI, System.js, webpack, starter seed:

  "@angular/cli": "^7.0.6",

**Comment by timbell** [comment] 2018-11-23 10:11
I had the same. I think the issue is with `rxjs-compat` - more info [here](https://github.com/ReactiveX/rxjs/issues/4070#issuecomment-418945390).

I fixed by pinning `rxjs-compat` to `6.2.2` in my `package.json`

**Comment by diegoserrat** [comment] 2018-11-23 13:05
Hi, thanks for you answer so fast!

I`ve done this steps: 

- npm un --save rxjs

- npm un --save rxjs-compat

- npm  list --depth=0 (in order to check that rxjs is removed, you should have a warning or an error at the end of the list)

-  npm i --save rxjs@6.2.2

- npm i --save rxjs-compat@6.2.2

and it worked! Thanks a lot!

**Closed as completed** 2018-11-26 10:19 UTC

**Comment by chetanladdha** [comment] 2020-05-08 07:07
We are using the below versions: Still, we see the issue: Any workaround available?
 "ngx-bootstrap": "2.0.5",
 "rxjs": "6.4.0",
 "rxjs-compat": "6.3.3"

**Comment by born2net** [comment] 2020-07-14 19:14
I am seeing same issue when upg from ng 9 to ng 10... I am not using this lib so maybe someone knows of a solution?

**Comment by petebacondarwin** [comment] 2020-07-15 10:22
Are you using `rxjs-compat`? This comment might be relevant: https://github.com/angular/angular-cli/issues/18045#issuecomment-651141100

**Comment by petebacondarwin** [comment] 2020-07-15 10:22
This comment might be relevant: angular/angular-cli#18045 (comment)
