### ISSUE TITLE
[typeahead] error on first onBlur wihtout adding input

### ISSUE THREAD

**Issue by woricek** [valor-software/ng2-bootstrap#5842] opened 2020-07-02 08:41 UTC
Bug description:
when clicking into typeahead input and clicking out, it throws error into console

Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-bootstrap-t2wtpd

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.6.2

Angular: 8

Bootstrap: 4

**Expected behavior**
typeahead should do nothing and not throw exception

**Comment by szh** [comment] 2020-07-24 13:27
Duplicate of https://github.com/valor-software/ngx-bootstrap/issues/5736

**Closed as completed** 2020-07-28 12:38 UTC
