### ISSUE TITLE
arrow keys don't scroll divs inside modals

### ISSUE THREAD

**Issue by TaylorShane** [valor-software/ng2-bootstrap#5916] opened 2020-08-27 19:43 UTC
Bug description:
When an element within a modal has a scroll-able area, the up and down keys don't scroll the content (as they do in every other scenario).

StackBlitz that reproduces the issue:
https://ngx-bootstrap-f4vxs5.stackblitz.io

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
"ngx-bootstrap": "5.6.1",

Angular:
"@angular/common": "~9.1.0",
"@angular/compiler": "~9.1.0",
"@angular/core": "~9.1.0",
"@angular-devkit/build-angular": "~0.901.0",
"@angular-devkit/build-ng-packagr": "~0.901.0",
"@angular/cli": "~9.1.0",
"@angular/compiler-cli": "~9.1.0",

Bootstrap:
4

**Expected behavior**
The area should scroll when using the appropriate arrow keys

**Comment by daniloff200** [comment] 2020-08-28 16:45
supposed to be duplicate of #5917

**Closed as completed by daniloff200** 2020-08-28 16:45 UTC
