### ISSUE TITLE
popover is jumping on hi-res monitors

### ISSUE THREAD

**Issue by Andrii-A** [valor-software/ng2-bootstrap#4855] opened 2018-11-29 16:52 UTC
### Bug:
Attached to body Popover is  jumping on hi-res monitors when Scale and layout in Display settings is not 100%. Inline positioning styles are constantly changing.

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 3.0.0
Angular: 6.0.6
Angular CLI 6.0.8
OS: WIndows 10

![image](https://user-images.githubusercontent.com/15634416/49237836-1c184d00-f3cd-11e8-823d-cc32991e544c.png)

**Comment by andreylopata-gh** [comment] 2018-12-28 10:17
@Andrii-A  Hello! Could you provide please more information about hi-res monitors, exactly what resolution?

**Comment by Andrii-A** [comment] 2018-12-28 15:10
Dell 4K

**Comment by andreylopata-gh** [comment] 2018-12-28 18:17
@Andrii-A Hey again! I could not reproduce this issue.

Please provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ludmilanesvitiy** [comment] 2019-03-19 11:18
Tested popover behaviour on hi-res monitors with 3.3.0 version, can't detect this issue anymore. Fixed in #5027

**Comment by ludmilanesvitiy** [comment] 2019-03-19 11:18
![Peek 2019-03-19 13-15](https://user-images.githubusercontent.com/18209841/54602136-7eaf5a80-4a49-11e9-81c4-f19d65e2d2e2.gif)

**Closed as completed by ludmilanesvitiy** 2019-03-19 11:18 UTC
Labels: issue, comp(popover)
