### ISSUE TITLE
bsDatepicker in reactive forms support for iso string

### ISSUE THREAD

**Issue by akvaliya** [valor-software/ng2-bootstrap#5148] opened 2019-04-04 11:39 UTC
I am using reactive forms in angular 7.

Now in my data all date fields are coming in iso string & i have to store as iso string in db too.

When i use bsDatepicker & do `patchValue` it displays` Invalid Date`.  

It should accept iso string. It is basic requirement for any date-picker. 

For now i have to remember every date component & have to convert all date fields to date object which changes data type to object from string & i am using DTO.  So this creates an issue.

Can anyone tell what am i missing here?

**Comment by ludmilanesvitiy** [comment] 2019-04-11 08:05
Closes as a duplicate of https://github.com/valor-software/ngx-bootstrap/issues/4487

**Closed as completed by ludmilanesvitiy** 2019-04-11 08:05 UTC
Labels: enhancement, comp(datepicker)
