### ISSUE TITLE
popover rendering slow

### ISSUE THREAD

**Issue by Ludevik** [valor-software/ng2-bootstrap#5261] opened 2019-06-10 15:30 UTC
### Bug description or feature request:
Popover rendering slow.
From my understanding from the code, the popover component now uses `locationService` and `calcPosition`. `calcPosition` is then called for each visible instance of popover on every scroll event which slows down rendering noticeably even in Chrome.

I am aware of `adaptivePosition` input on `popover.directive`, is setting this to false suggested solution for displaying many popovers? I would expect that `scroll` events are throttled or debounced because they happen so fast.

Furthermore what happens in our app after the upgrade from 3.1.3 to 4.3.0 is that whenever scroll event happens then our page components are being rerendered which slows down the whole app. I will investigate further why this happens, but if anyone has any hints what could cause that it will be helpful.

### Plunker/StackBlitz that reproduces the issue:

1. navigate to https://valor-software.com/ngx-bootstrap/#/popover in any browser (IE 11 being the slowest)
2. open ~10 popovers
3. scroll the page with scrollbar

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.3.0
Angular: 8.0.0
Bootstrap: 3.3.7

**Comment by Ludevik** [comment] 2019-06-11 12:02
I reproduced the issue with rerendering on [stackblitz](https://stackblitz.com/edit/angular-x9a8py).
Observe how render count goes up when scrolling. When i remove the popover from the component, rerendering doesn't happen.

**Comment by belinef** [comment] 2020-02-14 11:42
Looks like issue is not reproducible on latest version `5.5.0`
@IraErshova

**Comment by daniloff200** [comment] 2020-02-14 11:48
yeah, @belinef , I can agree, that also can reproduce it with latest version
Gonna close it for now

**Closed as completed by daniloff200** 2020-02-14 11:48 UTC
Labels: issue, enhancement, comp(popover), performance
