### ISSUE TITLE
Advanced daterange picker

### ISSUE THREAD

**Issue by hoangleitvn** [valor-software/ng2-bootstrap#5297] opened 2019-06-24 02:26 UTC
I would be nice if we can support a few options for daterange picker that allows user easy to select a relative date range
![image](https://user-images.githubusercontent.com/43955692/59986664-edf8a400-9661-11e9-90ec-2280d63d0a80.png)

**Comment by ludmilanesvitiy** [comment] 2019-06-24 11:56
Closed as a duplicate of https://github.com/valor-software/ngx-bootstrap/issues/5262

**Closed as completed by ludmilanesvitiy** 2019-06-24 11:56 UTC
Labels: comp(datepicker), feat-request
