### ISSUE TITLE
Datepicker month bug

### ISSUE THREAD

**Issue by sweetzhang** [valor-software/ng2-bootstrap#4396] opened 2018-05-30 08:10 UTC
### Bug description or feature request:
When I use ngx-bootstrap datepicker, the page just came in on May 31, I went to switch the month, clicked in June, but it came out in July.
(https://valor-software.com/ngx-bootstrap/old/2.0.4/#/datepicker)
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:2.0.2

Angular:4.0

Bootstrap:3

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

**Comment by H--o-l** [comment] 2018-05-31 12:13
Same here, with french locale, on May 31, if I click on the month and change to April, datepicker instead select May.
If I do it a second time it works.
The bug only happen for the last day of the month (here May **31**).

**Comment by clabnet** [comment] 2018-06-11 05:15
Same problem with italian format DD/MM/YYY. Paste 2004-10-04 on text field, the displayed result is 20/04/2010.
See https://stackblitz.com/edit/ngx-bootstrap-bsdatepicker-bug

**Comment by ghost** [comment] 2018-11-01 12:05
@sweetzhang can't reproduce in a new ngx-bootstrap version. Please try a new version.

**Comment by H--o-l** [comment] 2018-11-05 10:40
@svetoldo4444ka I retry with ngx-bootstrap v3.1.1, and I still have the [same issue](https://github.com/valor-software/ngx-bootstrap/issues/4396#issuecomment-393510633).
Can you re-open the issue ?

**Comment by H--o-l** [comment] 2018-11-22 16:00
Sorry to bother you @svetoldo4444ka but I just retested with bootstrap v3.1.2 and it is not fix there either.
It is not to critic your work, which is great by the way, but the bug should be tracked.
Otherwise you are at risk of misleading a bunch of developers and a few of them will keep opening this same issue.

**Comment by Domainv** [comment] 2018-11-22 16:07
@H--o-l re-opened. 
Could you provide some small repo with reproduction?
It's will help a lot

**Comment by H--o-l** [comment] 2018-11-27 13:46
> @H--o-l re-opened.

Thanks @Domainv !

>  Could you provide some small repo with reproduction?

Of course, I created one just here: https://stackblitz.com/edit/ngx-bootstrap-roobc2?file=app%2Fapp.component.ts

The Datepicker should be open, and a date selected.
So just click on "October" to change the month, choose November, and you will arrive in December.

Do not hesitate if you need more info !

**Comment by johnsmathew** [comment] 2019-01-08 11:49
> The Datepicker should be open, and a date selected.
> So just click on "October" to change the month, choose November, and you will arrive in December.

The current selected date is Oct 31, 2018. When November is chosen, system tries to set the date to Nov 31, 2018. Since there is no Nov 31, the date is pushed forward by 1 day to Dec 1, 2018. 

#4992 resets the day to 1 when a month is selected. So, when November is selected from month-selection view, the reference date would now be 1 Nov, 2018.

**Comment by H--o-l** [comment] 2019-01-08 13:19
Hi @johnsmathew, thanks for taking the time to look at this issue !

> The current selected date is Oct 31, 2018. When November is chosen, system tries to set the date to Nov 31, 2018. Since there is no Nov 31, the date is pushed forward by 1 day to Dec 1, 2018.

I agree that is the issue's trigger.

> #4992 resets the day to 1 when a month is selected. So, when November is selected from month-selection view, the reference date would now be 1 Nov, 2018.

Thanks for opening a PR to fix this, I now better understand the code.
But I think the solution do not make a natural UI, something like "if selected day not in month, set it to day 1, else re-use the selected day".
I will comment in the PR directly.

**Comment by livthomas** [comment] 2019-03-29 17:58
The bug is still there in version 4.2.0. If you go to [the documentation](https://valor-software.com/ngx-bootstrap/#/datepicker) today, open any datepicker, click on the month and select February, you will get to March instead.

**Comment by Domainv** [comment] 2019-03-29 19:16
@livthomas We don't have the version. 4.0.0 is the last.
And yes, for now, it not fixed yet

**Comment by livthomas** [comment] 2019-03-29 19:25
@Domainv Sorry, I meant **3.2.0**. Is 4.0.0 stable? Because 3.2.0 is the one marked as _latest_ on NPM and installed by default but I can see that there are already two newer versions (3.3.0 and 4.0.0).

**Comment by Domainv** [comment] 2019-03-29 19:39
@livthomas Yes, just not added as the latest.
4.0.1 in one hour be released 
On Monday I'll add it as the latest

**Comment by daniloff200** [comment] 2019-09-19 09:41
Well, looks like that was fixed in 5.2.0, in #5376 
looks similar to #5371

**Comment by ludmilanesvitiy** [comment] 2019-09-19 10:39
Closed as resolved in 5.2.0: https://valor-software.com/ngx-bootstrap/#/datepicker

**Closed as completed by ludmilanesvitiy** 2019-09-19 10:39 UTC
Labels: comp(datepicker), needs: reproduce, needs review
