### ISSUE TITLE
Bug: Nested collapse components height not correct (with animations)

### ISSUE THREAD

**Issue by ejasarevic** [valor-software/ng2-bootstrap#5249] opened 2019-06-05 12:39 UTC
### Bug description:
When using nested collapse elements, parent height is not calculated correctly before/after collapsing when using animations. If animations are not used, then it works as expected.

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-msp3wb

Steps to reproduce (with animations enabled):
1. Click on child collapse 1 and child collapse 2 to collapse them
2. Click on parent collapse to collapse
3. Click on parent collapse to expand
4. Click on any child to expand 
--------------------------------------
Result: Child is not completely visible as parent height/min-height/max-height is not correct anymore

However if you switch to the example without animations (button on the top) before step 1, it works as expected.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.2.0
Angular: 7.2.0 (also with v8)
Bootstrap: 4.0.0

**Comment by Domainv** [comment] 2019-06-05 13:11
Closes as duplicate of #5202

**Closed as completed by Domainv** 2019-06-05 13:11 UTC
Labels: comp(collapse)
