### ISSUE TITLE
How to pick the Date and Time at the same time

### ISSUE THREAD

**Issue by Ram12393** [valor-software/ng2-bootstrap#4551] opened 2018-08-17 05:32 UTC
I'm using  `ngx-bootstrap` to get the Datepicker using below link

[https://valor-software.com/ngx-bootstrap/#/datepicker](url) it works fine to get the datepicker. But I want to get the date and time using `ngx-bootstrap` . Is there any way to do this.?

**Comment by KerriDevine** [comment] 2018-09-06 23:03
We have a similar requirement. One possible solution would be to extend the `Input() container` to support other types besides 'body'. Currently, we are struggling to find a way to style the two components in the same pop-up as such:

![image](https://user-images.githubusercontent.com/13853364/45189512-ff6dde00-b1fe-11e8-8a5f-3ccf58d4f493.png)

**Comment by Ram12393** [comment] 2018-09-07 09:18
@KerriDevine You have posted screenshot  of both time and Date. Is it working ?? can you share your piece of code???

**Comment by Ram12393** [comment] 2018-09-07 09:19
[https://www.npmjs.com/package/ng-pick-datetime](url) you can the both Date and Time in one section using this NPM

**Comment by KerriDevine** [comment] 2018-09-07 15:50
@RamBM unfortunately that's just a mock-up of what I want it to look like. I haven't found a solution yet.

**Comment by Ram12393** [comment] 2018-09-07 17:18
Did you check previous URL which I provide above?

**Comment by Domainv** [comment] 2018-10-30 14:58
closed as duplicate of #551

**Closed as completed by Domainv** 2018-10-30 14:58 UTC
Labels: comp(datepicker), feat-request

**Comment by RamBM** [comment] 2018-10-31 04:39
what is the reason behind to close this question? I haven't any  reliable solution for this Question
