### ISSUE TITLE
Done/Close button in datepicker

### ISSUE THREAD

**Issue by UdayAppam** [valor-software/ng2-bootstrap#5795] opened 2020-05-26 10:49 UTC
How can we Done/Close button inside calendar panel for datepicker control.
Could you please help me.

`BsDatepickerContainerComponent` need  datepicker  ref to hide the datepicker panel.
How we would get the reference? Could you please share the inputs

**Comment by daniloff200** [comment] 2020-08-23 12:09
hello, @KernelLora 
is this a duplicate of #5835 ?

**Comment by UdayAppam** [comment] 2020-08-24 05:15
Yeah Somehow missed Closed the issue

**Closed as completed** 2020-08-24 05:14 UTC
Labels: enhancement
