### ISSUE TITLE
Date Range - Show current and previous month

### ISSUE THREAD

**Issue by ChaudhryAtif** [valor-software/ng2-bootstrap#5386] opened 2019-09-11 00:01 UTC
### Feature description or feature request:
Is it possible to show current and previous (instead of current and next) month in range picker if no range is selected?

### Plunker/StackBlitz that reproduces the issue:
Here is a workaround found on [SO](https://stackoverflow.com/a/53723196/4669619), but I am wondering if there's a cleaner way to do it (or if it can be baked into the library), and also to only do this behavior when a range is not selected already.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.1

Angular: 8.3.0

Bootstrap: 4.3.1

**Comment by daniloff200** [comment] 2019-09-13 09:38
@ChaudhryAtif  hey!
It's possible to create functionality, that allows to show prev  & current months, but, I want more info about the second part of your request

What do you mean by 
> also to only do this behavior when a range is not selected already.
?

As I understood, you want to keep the current and prev month only if no daterange was selected, but, if I did that, then, it should show current month and next? Or what?

**Comment by ChaudhryAtif** [comment] 2019-09-17 07:04
@daniloff200 If it is already selected, then it should follow current functionality: It'll show the starting date of the range on left and next month on the right.

**Comment by daniloff200** [comment] 2019-09-18 13:29
@ChaudhryAtif  okay, cool
gonna look at it, and what I can make here

**Comment by daniloff200** [comment] 2019-10-18 12:01
@ChaudhryAtif 

Hello ! I'm now working with that, and wanna ask one question, that  appeared during dev process

That's how it gonna work. For now it's October, but, you will see September too 
![Selection_036](https://user-images.githubusercontent.com/13692220/67092420-d10b5200-f1b7-11e9-93fe-87a870629d35.png)

But, when you choose daterange only in September (not touching October), when you open calendar again, you're still gonna see September & October, and not August & September
![Selection_037](https://user-images.githubusercontent.com/13692220/67092522-1465c080-f1b8-11e9-9bbc-538ae5eba2f0.png)

Does it correct for you? 

If you choose range with October in it, after opening calendar again, you will see October and November, the next month, as it worked before.

Waiting for your answer!

**Comment by ChaudhryAtif** [comment] 2019-10-18 13:37
@daniloff200 Thank you for working on this!

**Edit/Update:** I re-read your reply and I think I am saying the same thing below, so yes that is the desired behavior. Misunderstanding on my part!

===

Here's a rough example of expected outcome: https://stackblitz.com/edit/angular-mtluz4

Top picker is current behavior, bottom is desired feature (by a property, say showPreviousMonth="true")

If you open the top picker, it shows current (Oct) and next (Nov) month.
If you open the bottom picker, it shows previous (Sep) and current (Oct) month.

==

If you select a range on the top picker, the start date will become the month on the left, and it'll show next month on the right. For example: 8/10 - 8/14 (Aug on left, Sep on right). 11/10 - 12/10 (Nov on left, Dec on right).

If you select range on the bottom picker, it'll currently always show previous and current month (due to workaround/hack). What I meant by "also to only do this behavior when a range is not selected already." in my original post is that when the date range is selected, it should fall back to original functionality like the top picker.

I hope this helps. Again, thanks for working on this!

**Comment by daniloff200** [comment] 2019-10-18 20:44
@ChaudhryAtif  thanks for details and good example! Looks like my feature, works exactly the same, as in your demo! Hope it will be merged this week

**Comment by ChaudhryAtif** [comment] 2019-10-19 16:41
Perfect! Thank you for the effort!

**Comment by ChaudhryAtif** [comment] 2020-01-07 15:08
@daniloff200, it's been a while. Any update on this?

**Closed as completed** 2020-01-09 16:12 UTC
Labels: comp(datepicker), feat-request

**Comment by daniloff200** [comment] 2020-01-09 19:08
@ChaudhryAtif 
Sorry for the delay
Should be available in latest version, I supposed it's 5.4.0

**Comment by daniloff200** [comment] 2020-01-11 03:00
via Hubstaff
User: Dmitriy Danilov

Project: int_ngx-bootstrap (OSS) - https://app.hubstaff.com/projects/304822
Date Range: 10/18/19 - 10/20/19
Work session total: 1:48:15
Billable: Yes

Grand total: 1:48:15

**Comment by bunmiedee** [comment] 2020-10-27 12:34
@daniloff200 is there a way to avoid the current month moving to the left on date selection? I'd like to keep the previous month on the left at all times. 

Current behaviour: Assuming current month is October, When I open the date picker I see September and October. This is okay. When I select a date in October the view changes to October and November.

Expected behaviour: I'd like to have an option to keep the initial months  September and October after selecting a date in the current month

**Comment by daniloff200** [comment] 2020-10-27 12:37
@bunmiedee suppose you're talking about functionality described here : https://github.com/valor-software/ngx-bootstrap/issues/5968
It's some new feature request from another user on stackoverflow, I hope to make it in the next versions, but, right now, it's not possible

**Comment by bunmiedee** [comment] 2020-10-27 12:42
Ah yes! @daniloff200 this is exactly what I meant. Thanks for the update. Will keep an eye out for that

**Comment by kennylevi** [comment] 2022-09-28 11:25
is it possible to remove the second calendar, from the date range picker?
