### ISSUE TITLE
Tooltip not displayed properly

### ISSUE THREAD

**Issue by RihabEA** [valor-software/ng2-bootstrap#6492] opened 2022-07-26 09:07 UTC
Hello,

When we update the bootstrap from 5.1.3 to 5.2.0 and ngx-bootstrap from 8.0.0 to 9.0., there is an issue with position of the tooltip, related to an icon within a cell.

Kindly find below the two plunkers created to display the issue:

1- Current Behavior (bootstrap: 5.2.0): when we click the icon in the cell (price column), the tooltip appears in the wrong place

https://stackblitz.com/edit/current-behav-tooltip-not-dislaying-properly-in-the-grid?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

2- Expected behavior (using the old version 5.1.3): when we click the icon in the cell, the tooltip open in the right place

https://stackblitz.com/edit/expected-beha-tooltip-dislaying-properly?file=package.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

**_### Note:
Angular version: 14.0.6
Ag-grid version: 28.0.2
Bootstrap: 5.2.0
ngx-bootstrap: 9.0.0_**

**Comment by damient** [comment] 2022-07-26 18:32
Duplicate of https://github.com/valor-software/ngx-bootstrap/issues/6490

**Comment by emonney** [comment] 2022-07-29 13:02
Temp workaround is to add this to your stylesheet:

.popover {
  position: absolute;
  top: 0;
  left: 0 #{"/* rtl:ignore */"};
}

.popover-arrow {
  position: absolute;
}

.tooltip {
  position: absolute;
}

.tooltip-arrow {
  position: absolute;
}

**Comment by RihabEA** [comment] 2022-08-01 09:03
Thanks for your help, it works from my side!!

**Comment by probit2** [comment] 2022-12-29 13:13
> Temp workaround is to add this to your stylesheet:
> 
> .popover { position: absolute; top: 0; left: 0 #{"/* rtl:ignore */"}; }
> 
> .popover-arrow { position: absolute; }
> 
> .tooltip { position: absolute; }
> 
> .tooltip-arrow { position: absolute; }

I got the same issue When I update the bootstrap from 5.1.0 to 5.2.3 and ngx-bootstrap from 8.0.0 to 9.0.0

But it is fixed when I used this CSS in my stylesheet file

My current project packages
Angular version: 14.2.12
Bootstrap: 5.2.3
ngx-bootstrap: 9.0.0

Thanks,
Kishan

**Closed as completed** 2023-01-05 07:34 UTC

**Comment by Shahed1998** [comment] 2023-06-01 18:18
Thank you it works @emonney

**Comment by KrishnaRathore** [comment] 2023-06-09 13:45
Thank you  @emonney

**Comment by ertzoc** [comment] 2023-11-22 17:32
Thanks @emonney
