### ISSUE TITLE
ngx-bootstrap/index.d.ts, found version 4, expected 3,

### ISSUE THREAD

**Issue by Vittalks** [valor-software/ng2-bootstrap#4393] opened 2018-05-29 08:23 UTC
ngx-bootstrap@3.0 with angular 4.4 

error: 

ERROR in Error: Metadata version mismatch for module node_modules/ngx-bootstrap/index.d.ts, found version 4, expected 3, resolving symbol AppModule in src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts, resolving symbol AppModule in src/app/app.module.ts
    at syntaxError (node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**after run ng serve**

will receive below error 
ERROR in ./node_modules/ngx-bootstrap/datepicker/bs-daterangepicker.component.js
Module not found: Error: Can't resolve 'rxjs/operators' in '/node_modules/ngx-bootstrap/datepicker'
resolve 'rxjs/operators' in '/node_modules/ngx-bootstrap/datepicker'
  Parsed request is a module
  using description file: /node_modules/ngx-bootstrap/package.json (relative path: ./datepicker)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /node_modules/ngx-bootstrap/package.json (relative path: ./datepicker)
    resolve as module
      /node_modules/ngx-bootstrap/datepicker/node_modules doesn't exist or is not a directory
      /node_modules/ngx-bootstrap/node_modules doesn't exist or is not a directory
      /node_modules/node_modules doesn't exist or is not a directory
      /Users/Mac1/yoobikwiti/node_modules doesn't exist or is not a directory
      /Users/Mac1/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /node_modules
        using description file: /package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /package.json (relative path: ./node_modules)
          using description file: /node_modules/rxjs/package.json (relative path: ./operators)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /node_modules/rxjs/operators doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /node_modules/rxjs/operators.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /node_modules/rxjs/operators.js doesn't exist
            as directory
              /node_modules/rxjs/operators doesn't exist

**Comment by oscarnascimento** [comment] 2018-05-29 14:44
ERROR in Metadata version mismatch for module PROJECT_PATH/node_modules/ngx-bootstrap/pagination/index.d.ts, found version 4, expected 3, resolving symbol SharedModule

Please, help us

**Comment by roenschg** [comment] 2018-05-30 12:07
We also have the same issue. I tried changing the version in the index.metadata.json but it did not help

**Comment by Vittalks** [comment] 2018-05-30 12:24
@roenschg you can add ngx-bootstrap@2.0.5 - it's work fine with angular 4.4

**Comment by plalithkumar9190** [comment] 2018-06-26 14:15
im getting 'ts' not found error. because of 'ngx-bootstrap/datepicker' module. other popover and modal modules are working fine. please help to resolve this.
using...
- Angular v4
- bootstrap v3 
note : i was try this in 'ngx-bootstrap' v2.0.5 and as well as latest v3.0.1

**Comment by SerCrAsH** [comment] 2018-06-28 08:18
In package.json :
Failed with:    ` "ngx-bootstrap": "^3.0.1",`
Worked with: `"ngx-bootstrap": "^2.0.0-beta.9",`

**Comment by ghost** [comment] 2018-11-12 11:19
@SerCrAsH could you please update your ngx-bootstrap package to the latest version(3.1.1) and if something goes wrong provide a reproduction of this issue. 
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by valorkin** [comment] 2018-11-12 12:28
ngx-bootstrap v3 works with angular v6 and v7
ngx v2 with angular v2 and v4 as far as I remember
Angular v4 -> v6 has breaking changes, this is why ngx-boostrap had major version bump

**Closed as completed by valorkin** 2018-11-12 12:28 UTC
Labels: question, comp(build), needs: reproduce
