### ISSUE TITLE
Typeahead slows down when list increases more than 500

### ISSUE THREAD

**Issue by imtiazShakil** [valor-software/ng2-bootstrap#5695] opened 2020-02-27 12:09 UTC
Bug description:
Typeahead takes a lot of time to render list when `typeaheadOptionsLimit` gets more than 500. When performing performance check in chrome browser we can see sometime it takes more than couple of seconds.

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-typeahead-angular-8-bug?embed=1&file=src/app/app.component.html

Versions:

- ngx-bootstrap: ^5.2.0

- Angular: ^8.3.13

Build system: Angular CLI

**Expected behavior**

The rendering should not take that much. It needs to improve

**Comment by sonicpro** [comment] 2020-02-27 13:32
I'm going to look into this.

**Comment by daniloff200** [comment] 2020-02-27 14:07
it was discussed in https://github.com/valor-software/ngx-bootstrap/issues/5309

I suggest to upgrade to 5.5.0, but, even with that version performance will be not 100% cool

**Comment by imtiazShakil** [comment] 2020-03-02 10:26
latest npm version (5.3.2) is behind current version (5.5.0).

> but, even with that version performance will be not 100% cool

Please update npm version, so we can atleast have less than 100% coolness ;)

**Comment by daniloff200** [comment] 2020-06-15 13:44
Should we available for now,  check 5.6.2 as the latest version right now

gonna close it as duplicate of #5309

**Closed as completed by daniloff200** 2020-06-15 13:44 UTC
